version: 0.0
os: linux

files:
  - source: .
    destination: /home/ec2-user/petpick-deploy

permissions:
  - object: /home/ec2-user/petpick-deploy
    owner: ec2-user
    group: ec2-user
    mode: '755'
    type:
      - directory
      - file
  - object: /home/ec2-user/petpick-deploy/scripts/*
    owner: ec2-user
    group: ec2-user
    mode: '755'
    type:
      - file

hooks:
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 200
      runas: ec2-user


