spring.application.name=

# Import .env file
spring.config.import=optional:file:.env[.properties]

# DB
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Google OAuth2 Client
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile, email
spring.security.oauth2.client.registration.google.redirect-uri=${BACKEND_BASE_URL}/login/oauth2/code/google

# JWT
jwt.jwt-key=${JWT_SECRET_KEY}
jwt.jwt-expiration=${EXPIRATION}
jwt.jwt-refresh-expiration=${REFRESH_EXPIRATION}

# OIDC
spring.security.oauth2.client.provider.google.issuer-uri=https://accounts.google.com
